# Generated by Django 2.2.5 on 2019-11-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Meat', models.IntegerField()),
                ('Cheese', models.IntegerField()),
                ('Salad', models.IntegerField()),
                ('Bacon', models.IntegerField()),
                ('Fee', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('Note', models.TextField()),
                ('consigneeName', models.CharField(max_length=20)),
                ('consigneeAddress', models.TextField()),
                ('consigneeTel', models.IntegerField()),
            ],
        ),
    ]
